version: '3'
services:
      nginx:
        image: nginx:latest
        volumes:
          - ./nginxcfg/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
        restart: always
      mariadb:
        image: mariadb:latest
        restart: always
        volumes:
          - ./mariadb_data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: Test123TEST
          MARIADB_USER: user1
          MARIADB_PASSWORD: user1paSS
      phpmyadmin:
        image: phpmyadmin
        restart: always
        #ports:
        #  - 8091:80
        environment:
          - PMA_ARBITRARY=1
